[package]
name = "word-search"
version = "0.1.0"
authors = ["Alex <busarovalex@yandex.ru>"]

[dependencies]
structopt = "0.1.0"
structopt-derive = "0.1.0"
env_logger = "0.5.3"
log = "0.4.0"

[profile.dev]
debug=true
opt-level=0

[profile.release]
debug = true
lto = false

[features]
unsafe = []
